import = [
	# auto-configured by `theme` function
	 "~/.config/alacritty/selected-theme.toml",
 ]

[window]
decorations = "Buttonless"
padding = { x = 20, y = 25 }
option_as_alt = 'Both'

[font]
normal = { family = "SF Mono", style = "Regular" }
size = 12
offset = { x = 1, y = 8 }
glyph_offset = { x = 0, y = 4 }

[mouse]
hide_when_typing = true

[shell]
program = "/opt/homebrew/bin/fish"
args = [ "--login" ]

[debug]
# render_timer = true
