# Colors (Everforest Dark)
# https://github.com/sainnhe/everforest

# Default colors
[colors.primary]
background     = '#2d353b'
foreground     = '#d3c6aa'
dim_foreground = '#56635F'

# Normal colors
[colors.normal]
black   = '#475258'
red     = '#e67e80'
green   = '#a7c080'
yellow  = '#dbbc7f'
blue    = '#7fbbb3'
magenta = '#d699b6'
cyan    = '#83c092'
white   = '#d3c6aa'

# Bright colors
[colors.bright]
black   = '#475258'
red     = '#e67e80'
green   = '#a7c080'
yellow  = '#dbbc7f'
blue    = '#7fbbb3'
magenta = '#d699b6'
cyan    = '#83c092'
white   = '#d3c6aa'

# Dim colors
[colors.dim]
black   = '#232A2E'
red     = '#514045'
green   = '#425047'
yellow  = '#4d4c43'
blue    = '#3a515d'
magenta = '#543a48'
cyan    = '#83c092'
white   = '#56635f'

[colors.selection]
text = 'CellForeground'
background = '#3d484d'
